### ISSUE TITLE
Json parse error

### ISSUE THREAD

**Issue by dkdl** [voronianski/soundcloud-audio.js#13]
Since last week I get the following error:
    SyntaxError: Unexpected token ':'. Parse error.

I guess this has to do with SoundCloud updating (GO Update), but I'm not sure how to fix it.

**Comment by sbauch** [comment]
It looks to me like /resolve is no longer supporting JSONP but is instead returning a JSON body.

I've got a branch that addresses this issue and uses the JSON response that is returned by Soundcloud.

I'm not sure whether to submit a PR as it is unclear to me whether this is an error on Soundcloud's side or if they no longer support JSONP.

My branch is here - https://github.com/sbauch/soundcloud-audio.js

@voronianski what do you think about a PR for this? I've email soundlcoud API support, posted an SO question, and have been tweeting at their support handle to try to get to the bottom of this.

**Comment by voronianski** [comment]
@sbauch thanks, could you please share SO link and your tweet so I can join a discussion. If there is such change then PR will be welcome!
