### ISSUE TITLE
Doesn't work with Safari's DNT header

### ISSUE THREAD

**Issue by denkristoffer** [voronianski/soundcloud-audio.js#16]
This isn't really soundcloud-audio.js's fault, but maybe we can think of a way around this problem together?

The way that the SoundCloud API's CORS is currently set up, it rejects requests with the DNT header. Unfortunately it seems like [Safari adds this header on its own](https://stackoverflow.com/questions/39354408/safari-rejects-redirected-cors-request-due-to-browser-set-headers) to all XHR requests when the setting is enabled, which gives us the following result:
<img width="552" alt="screen shot 2017-01-24 at 22 25 52" src="https://cloud.githubusercontent.com/assets/219017/22267500/4e07dddc-e284-11e6-9ad9-eccf82e3b5f9.png">
Current versions of Safari don't support Fetch either, so that won't help here. Can you think of other possible solutions that won't leave DNT-enabled users left out?

I've written SoundCloud's dev account on Twitter about this so hopefully they're willing to whitelist the DNT header.

**Comment by sachse** [comment]
I've just tried with Safari Technology Preview, it *seems* to work even without using Fetch. I'll try to investigate further.

**Comment by voronianski** [comment]
@sachse thanks!

**Comment by denkristoffer** [comment]
This is no longer an issue in Safari Technology Preview, so the technical issue of the header being added automatically seems to have been solved. I haven't heard back from SoundCloud at all after trying to reach them in a few different ways though, so this is still going to be an issue for anyone using a stable version of Safari with DNT enabled. It doesn't seem like we can do anything about that, unfortunately 😒 

Might as well close this.
