### ISSUE TITLE
Set Volume / Volume Fade on play()/pause()

### ISSUE THREAD

**Issue by dennisausbremen** [voronianski/soundcloud-audio.js#17]
Would be great to have the options to set the tracks volume or even set a fadeIn/fadeOut on play()/pause() .

**Comment by voronianski** [comment]
@dennisausbremen PRs are always welcome 😉

**Comment by dennisausbremen** [comment]
I'm on it as soon as i find the time. :)

**Comment by dennisausbremen** [comment]
Not really ready for primetime, but it's a start.
https://codepen.io/dennisausbremen/pen/NpYdxq?editors=0010

**Comment by voronianski** [comment]
`setVolume` is available in latest version.
