### ISSUE TITLE
Submit new npm release?

### ISSUE THREAD

**Issue by gil--** [voronianski/soundcloud-audio.js#19]
Currently the latest npm release does not have the new setTime() function. Can you do a new npm release with setTime?

Local Error:
`Uncaught TypeError: _soundcloud.scPlayer.setTime is not a function`

https://github.com/voronianski/soundcloud-audio.js/compare/1.1.0...master

**Comment by gil--** [comment]
Also, as a follow up. I'm struggling to figure out how to use seek() or setTime().

Basically, how would I on page load, begin playing the at a specific point, say 6 seconds into the song?

##### Currently I have (this works):
```
scPlayer.audio.currentTime = 6;
scPlayer.play();
```

But I'm trying to figure out what seek or setTime do as I thought seTime would work but it doesn't seem to.

something like...
```
scPlayer.setTime(6);
scPlayer.play();
```

What am I missing?

**Comment by voronianski** [comment]
@gil-- should be ok now, update to version `1.1.1`.
