### ISSUE TITLE
Is it possible to get an Audio Buffer?

### ISSUE THREAD

**Issue by FireController1847** [voronianski/soundcloud-audio.js#20]
**Question**
Hello! I'm trying to develop a Discord Bot, and I need to know if it's possible to create a buffer when it plays. 

**Example**
Basically, it would be able to work by doing this:
```js
let buffer = <module>.<functionname>(url)
buffer.pipe(fs.createWriteStream("audio.mp3"));
```

**Comment by voronianski** [comment]
@FireController1847 this module is browser only.

**Comment by FireController1847** [comment]
Damn.
