### ISSUE TITLE
[Request] Add support for resolving playlist from array or json prop

### ISSUE THREAD

**Issue by ridhwaans** [voronianski/soundcloud-audio.js#30]
Currently, `soundcloud-audio` resolves by `url` and `client id` and makes a call to `api.soundcloud` to get playlist.tracks. 
To use a playlist from other audio sources, I would like to see `soundcloud-audio` use a key value array or json list of `playlist.track audio url` and `playlist.track index` passed as a prop, so that it works with soundplayer controls like Next & Previous

**Comment by voronianski** [comment]
this module is working only with soundcloud api, if you want to manage custom playlist it depends on your format, so you need to do it inside your app
