### ISSUE TITLE
custom start time not resolving

### ISSUE THREAD

**Issue by dkdl** [voronianski/soundcloud-audio.js#5]
Hello,

first, thank you for this great plugin! The only problem is when I give a custom start time with the url.
Example: https://soundcloud.com/balamii/dj-sotofett-b2b-brian-not-brian-jayda-g-jan-2016#t=13:10

The t=13:10 tells soundcloud to start at the 13th minute of the song. But it gives the following error: Failed to load resource: the server responded with a status of 401 (Unauthorized).

Any idea what could cause this?

**Comment by voronianski** [comment]
@dkdl thanks, I will take a look

**Comment by voronianski** [comment]
@dkdl support for custom start time was added in `1.0.0`.

**Comment by dkdl** [comment]
@voronianski thank you so much :+1:
