### ISSUE TITLE
Few notable updates for documentation

### ISSUE THREAD

**Issue by davey-h** [voronianski/soundcloud-audio.js#6]
You've done fantastic work with this. Wanted to give you a few heads up on changes that I presume come from changes in the SoundCloud API

## Resolve
*Your example*:
```javascript
scPlayer.resolve('https://soundcloud.com/djangodjango/first-light', function (err, track) {
     ...
});
```

here `err` and `track` have swapped places to 

```javascript
scPlayer.resolve('https://soundcloud.com/djangodjango/first-light', function (track, err) {
     ...
});
```

## TimeUpdate
*Your example*:
```javascript
scPlayer.on('timeupdate', function (audio) {
    console.log(audio.currentTime);
});
```
I thought I had this figured out but I don't. The event is working right, but I'm not seeing the `currentTime` property come in. As a workaround I'm currently grabbing the current time from `scPlayer.audio.currentTime` when the event fires.

I'll update this if I find more. Sorry if this is the wrong place to notify, new to this contributing game :smile:

**Comment by voronianski** [comment]
@davey-h thanks, I've updated README file.
