### ISSUE TITLE
resolving multiple tracks separately sometimes fails silently

### ISSUE THREAD

**Issue by sbauch** [voronianski/soundcloud-audio.js#9]
Per https://github.com/soundblogs/react-soundplayer/issues/34, I and at least one other are having issues with resolve() being called multiple times in quick succession.

Is it possible that jsonp callback script tags that are added to the DOM may be overriding a previous script tag? i.e., `(new Date()).valueOf()` is not unique enough?

https://github.com/voronianski/soundcloud-audio.js/blob/master/dist/soundcloud-audio.js#L82

**Comment by voronianski** [comment]
@sbauch please try latest `1.0.2`.

**Comment by sbauch** [comment]
seems to not make a difference (it may be helpful if you mentioned what changed as I'm not seeing much in the diff)

here's a screenshot of the requests panel from dev tools. 
![screen shot 2016-06-14 at 1 04 24 pm](https://cloud.githubusercontent.com/assets/923033/16052257/62d4e3c6-3231-11e6-878f-4ee366a1c847.png)

youll see that there are 3 calls to the resolve endpoint for different tracks that have the same callback param. 

something as simple as 

`var id = 'jsonp_callback_' + (new Date()).valueOf() + Math.floor(Math.random()*101);`

fixes this for me. 

Happy to do a PR, but let me know your thoughts here.

**Comment by voronianski** [comment]
@sbauch https://github.com/voronianski/soundcloud-audio.js/commit/d297d9fee6f0bb2aed20fefc85eb5b0c27895c41 we have such fix in 1.0.2

**Comment by voronianski** [comment]
@sbauch oops, sorry build  was wrong, now it should be fine in 1.0.3 - https://github.com/voronianski/soundcloud-audio.js/commit/eebafc89d76b6ec120340d43c7b8d286332cda6d
